#!/bin/sh
# -*- coding: utf-8-unix -*-

DIR="$(cd "$(dirname "${0}")"; pwd)"
TOP_DIR="$(cd "$(dirname "${DIR}")"; pwd)"
BIN_DIR="${TOP_DIR}/bin"
LIB_DIR="${TOP_DIR}/lib"
TEST_DIR="${TOP_DIR}/test"

PATH="${PATH}:${BIN_DIR}:${LIB_DIR}"

. xtest.sh

for x in "${TEST_DIR}/test"* ; do
    [ -f "${x}" ] || continue
    . "${x}"
done

xtest_runtest
