#!/bin/sh
# -*- coding: utf-8-unix -*-

DIR="$(cd "$(dirname "${0}")"; pwd)"
TOP_DIR="$(cd "$(dirname "${DIR}")"; pwd)"
BIN_DIR="${TOP_DIR}/bin"
LIB_DIR="${TOP_DIR}/lib"
TEST_DIR="${TOP_DIR}/test"

PATH="${PATH}:${BIN_DIR}:${LIB_DIR}"

. xtest.sh

data 'dataset #2' <<EOF
a:b:c   a   b   c
d:e:f   d   e   f
EOF

with 'dataset #2' as expected xs
xtest 'split " ", join ":" ($xs) -> ($expected)' : <<-'EOF'
	local ys
	IFS=' ' set - ${xs}
	IFS=':' ys=${*}
	assert "${expected}" = "${ys}"
	EOF
